# Path Planning
STEERING_METHOD = "autonomous"  # "user"/"autonomous"
BLANK_MAP = False  # use blank map at the start
EPISODE_TIME_LIMIT = 100
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PIXELS_PER_UNIT = 32

# SLAM
SLAM_ACTIVATED = False
SLAM_NOISE = 1e-3
SLAM_FRAME_LIMIT = 1  # "run slam every x seconds"
MATRIX_SIZE = 300

# Car
STEERING_NOISE = 1e-3
CAR_X_START_POSITION = 7
CAR_Y_START_POSITION = 10
CAR_LENGTH = 1.5
MAX_STEERING = 25
MAX_ACCELERATION = 4.0
MAX_VELOCITY = 4.0
BRAKE_DECELERATION = 4
FREE_DECELERATION = 1
CAR_FIELD_OF_VIEW = 225
CAR_FOV_RANGE = 60
TURNING_SHARPNESS = 1.8


