frequency: 50

two_d_mode: true

publish_tf: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: /odometry

imu0: /imu

odom0_config: [
  true, true, false,
  false, false, false,
  false, false, false,
  false, false, true,
  false, false, false
]

imu0_config: [
  false, false, false,
  false, false, true,
  false, false, false,
  false, false, true,
  true, false, false
]

predict_to_current_time: true
transform_time_offset: 1
